spring.application.name=Connection-to-SWAPI

spring.datasource.url=jdbc:postgresql://ep-tiny-thunder-acnjp0ah.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
jwt.secret-key=${JWT_SECRET_KEY}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
